# Generated by Django 5.2.3 on 2025-07-04 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='context',
            new_name='main_context',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='image',
            new_name='main_image',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='main_title',
        ),
        migrations.AddField(
            model_name='news',
            name='sub_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='NewsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('context', models.TextField(blank=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='news.news')),
            ],
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/additional/')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='news.news')),
            ],
        ),
    ]
