# Generated by Django 5.2.3 on 2025-07-04 15:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_options_rename_context_news_main_context_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='main_context',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='newsdetail',
            name='context',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
