# Generated by Django 5.2.3 on 2025-07-31 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_main_context_alter_newsdetail_context'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsDetail',
        ),
    ]
