# Generated by Django 5.2.3 on 2025-07-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_news_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='sub_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
