# Generated by Django 5.2.3 on 2025-08-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_make_subtitle_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsimage',
            name='title',
            field=models.CharField(blank=True, help_text='Bu görsel için isteğe bağlı başlık', max_length=200, null=True),
        ),
    ]
