# Generated by Django 5.2.3 on 2025-06-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_image_product_main_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
