# Generated by Django 5.2.3 on 2025-07-31 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_slug_alter_product_main_context_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDetail',
        ),
    ]
