# Generated by Django 5.2.3 on 2025-08-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_make_slug_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='description',
            field=models.TextField(blank=True, help_text='Bu görsel için isteğe bağlı açıklama', null=True),
        ),
    ]
