# Generated by Django 5.2.3 on 2025-08-26 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_options_product_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='products/documents/')),
                ('title', models.CharField(default='', help_text='PDF için başlık (örn: Teknik Şartname, Katalog)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Bu doküman için isteğe bağlı açıklama', null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='products.product')),
            ],
        ),
    ]
